[project]
name = "pydantic-demos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "pydantic-ai>=1.0.6",
    "pydantic-evals>=1.0.6",
]
